### ISSUE TITLE
Unwanted </p> tag - README.md

### ISSUE THREAD

**Issue by vishal-lokare** [vishal-lokare/AutoJoomer#102]
There's an unwanted </p> tag after the last table tag in README.md which is visible on the hosted GitHub webpage, just remove that.

**Comment by praguru14** [comment]
Hi Can you assign this to me?

**Comment by iusamahub** [comment]
HI! you can assign it to me

**Comment by Brymmobaggins** [comment]
Hello, can I work on this?

**Comment by NgoQuocBao1010** [comment]
> Hi Can you assign this to me? I think I can solve this issue for you @vishal-lokare

I also think I can solve this. Can you assign me for this problem?

**Comment by vishal-lokare** [comment]
Assigned to first comment - @praguru14, will assign to next person if not done before 17th ends IST.

**Comment by vishal-lokare** [comment]
done in #107
