### ISSUE TITLE
2. Readme rewrite, some documentation

### ISSUE THREAD

**Issue by vishal-lokare** [vishal-lokare/AutoJoomer#134]
More details in the discord server.

**Comment by NXPY123** [comment]
I would like to claim this issue and get more info on it

**Comment by vishal-lokare** [comment]
> I would like to claim this issue and get more info on it

Tag any maintainer in #boss-general channel on AutoJoomer server.

**Comment by NXPY123** [comment]
Name: Neeraj P Yetheendran
Roll No:2021bcs106
