### ISSUE TITLE
14. Login page

### ISSUE THREAD

**Issue by vishal-lokare** [vishal-lokare/AutoJoomer#146]

**Comment by motaboii** [comment]
Proposal selected, commenting for assigning.

**Comment by Biswadeepgiri** [comment]
I would like to work on this issue.
Name-Biswadeep Giri
Roll no-2021BCS0151
Email-biswadeep21bcs151@iiitkottayam.ac.in

**Comment by vishal-lokare** [comment]
> I would like to work on this issue. Name-Biswadeep Giri Roll no-2021BCS0151 [Email-biswadeep21bcs151@iiitkottayam.ac.in](mailto:Email-biswadeep21bcs151@iiitkottayam.ac.in)

Hey Biswadeep, this issue has been claimed by @motaboii , he has already sent a proposal and got selected. You can look for another issue.
