### ISSUE TITLE
Contributors button does nothing

### ISSUE THREAD

**Issue by SRR-CODER** [vishal-lokare/AutoJoomer#174]
**Describe the bug**
On clicking the 'contributions' button in popup, nothing happens.

**To Reproduce**
1. Click on 'Popup'
2. Click on 'Contributions'

**Expected behavior**
It should open a contributions page

**Screenshots**
![image](https://user-images.githubusercontent.com/78961362/193467429-cdbd311b-c9f2-4558-a9a1-2a36d70faa13.png)

**Comment by shashank1503-cipher** [comment]
Shall I work on this

**Comment by SRR-CODER** [comment]
Already on it.
