### ISSUE TITLE
Fix AutoJoomer logo not showing in README

### ISSUE THREAD

**Issue by vishal-lokare** [vishal-lokare/AutoJoomer#182]
The AutoJoomer logo on top of the README is wrongly referenced, fix the URL of it.
<img width="446" alt="image" src="https://user-images.githubusercontent.com/31512838/194134892-5f5da0de-cd80-4427-a2e7-9113ac4097e0.png">

**Comment by DPRIYATHAM** [comment]
I am Interested to work on this issue.
