### ISSUE TITLE
LMS button opens only lms.iiitkottayam.ac.in

### ISSUE THREAD

**Issue by vishal-lokare** [vishal-lokare/AutoJoomer#186]
LMS button should open [https://lms.iiitkottayam.ac.in](https://lms.iiitkottayam.ac.in) for 2020 batch
and [https://lmsone.iiitkottayam.ac.in](https://lmsone.iiitkottayam.ac.in) for 2019 and 2021 batch

**Comment by NNL-Keerthana** [comment]
I am interested on this issue

**Comment by NNL-Keerthana** [comment]
I am interested on this issue

**Comment by vishal-lokare** [comment]
Completed
