### ISSUE TITLE
Branch isn't displayed correctly on Login Page.

### ISSUE THREAD

**Issue by DPRIYATHAM** [vishal-lokare/AutoJoomer#187]
**Description of the bug**

After entering the AutoJoomer username, it is not showing the branch, value correctly at the respective place, instead, it's having a fixed value all the time.
The value we are assigning for the Branch in the login page isn't assigned properly, it is displaying the default value CSE after logging in and not getting updated after.

**Screenshots**

![image](https://user-images.githubusercontent.com/94455615/194764086-eaf5642d-42a8-4dbf-809f-0729db2c284c.png)

![image](https://user-images.githubusercontent.com/94455615/194764112-7645a4af-ebc8-49fe-9987-66d480a414a4.png)

**Expected behaviour**

It should Display the branch as **ECE** and **CSY** in the 1st, and 2nd screenshots.

**Comment by DPRIYATHAM** [comment]
I am willing to solve this issue.

**Comment by vishal-lokare** [comment]
Completed
