### ISSUE TITLE
Fix the borders of buttons inpopup.html

### ISSUE THREAD

**Issue by vishal-lokare** [vishal-lokare/AutoJoomer#193]
The bottom borders are not visble and left border for "Login", add proper and equal borders to the buttons.

<img width="303" alt="image" src="https://user-images.githubusercontent.com/31512838/195419680-b55cb8a8-5543-4db2-aa59-380e4f904d16.png">

**Comment by Maryam-Momoh** [comment]
Hello, I would like to work on this task

**Comment by NNL-Keerthana** [comment]
I am interested to work on this issue. Please assign it to me.

**Comment by Aditya-Shitale** [comment]
Please assign this issue to me, will complete it ASAP
