### ISSUE TITLE
Auto joomer req for 2022 batch

### ISSUE THREAD

**Issue by Srivathsa25** [vishal-lokare/AutoJoomer#212]

**Comment by vishal-lokare** [comment]
If you are interested to work on the issue, can you send me a message on LinkedIn https://www.linkedin.com/in/vishal-lokare/

**Comment by Srivathsa25** [comment]
> @Srivathsa25  If you are interested to work on the issue, can you send me a message on LinkedIn https://www.linkedin.com/in/vishal-lokare/

I will be glad to be a part of your team, but I am just a fresher, even our technical clubs haven't started. But if you feel i can help you by any means.

I will look forward to being part of your team

**Comment by abdul2801** [comment]
I'm interested in working on this issue.
Is this project still active?
