### ISSUE TITLE
roll number does not exist

### ISSUE THREAD

**Issue by unworld11** [vishal-lokare/AutoJoomer#213]
While attempting to login
it shows roll number does not exist for 2022 batch

**To Reproduce**
1. Go to login
2. Input Roll 2022BEC0013 psswd
4. click on login
5. See error

**Expected behavior**
It should log me in

**Screenshots**
<img width="1440" alt="Screenshot 2022-12-28 at 11 53 21 PM" src="https://user-images.githubusercontent.com/64916545/209856430-e95dfed1-a151-4c2f-aa7b-360fec7763a1.png">

**Desktop (please complete the following information):**

 - OS: macOS
 - Browser Chrome
 - Version  107.0.5304.110

**Comment by vishal-lokare** [comment]
Same as #227 . Closing.
