### ISSUE TITLE
[2] src/pages/login/popup.html, style.css - Fix the popup size issue

### ISSUE THREAD

**Issue by vishal-lokare** [vishal-lokare/AutoJoomer#220]
When you open the extension now, this is how it looks -
![image](https://github.com/vishal-lokare/AutoJoomer/assets/31512838/dc256ac5-0d9f-40af-b062-6e725d8543b1)

But it should look like - 
![image](https://github.com/vishal-lokare/AutoJoomer/assets/31512838/d71fccd5-7423-46da-8ea9-b8893888bfb6)

**Comment by Precizne** [comment]
Fixed in #237
