### ISSUE TITLE
Want to remove scrollbar from the rightmost side for the better appearance of the website

### ISSUE THREAD

**Issue by pra9patil** [vishal-lokare/AutoJoomer#238]
Hey @vishal-lokare Sir ,
How are you , I hope you are doing well 
I go through AutoJoomer website and I realized that we can enhance the appearance of the website by removing tha scroll bar from the top right most side by using simple CSS 
So my request to you sir will you please assign me this issue under hactoberfest I will work on it today itself 

Thank You

**Comment by prerit2001** [comment]
Please assign me under hactoberfest and hactoberfest-accepted label

**Comment by vishal-lokare** [comment]
The website is not open-source, this repo is only for the extension hosted on the Chrome Webstore. We will open source it later, not anytime soon.
