### ISSUE TITLE
Add an alert sound for classes opening. - script.js

### ISSUE THREAD

**Issue by vishal-lokare** [vishal-lokare/AutoJoomer#66]

**Comment by rounit08** [comment]
@vishal-lokare Can I take this?

**Comment by vishal-lokare** [comment]
> @vishal-lokare Can I take this?

Hey @rounit08 , thank you for showing interest in our open source project, but this issue has already been assigned to @karynaur and since this is an institute specific project, we are encouraging students from our college to contribute and learn more. I hope you understand.
